### ISSUE TITLE
When biome listed in Disabled Biomes, fog appears

### ISSUE THREAD

**Issue by Y0ungSandwich** [Hennamann/Fog-World#4]
Tried to disable the fog in "Desert" yet the fog persists through config changes. Doesn't matter what biome I put in the config the same thing happens. 

Version: FogWorld-1.12-1.1.0-b15-universal

**Comment by Hennamann** [comment]
Where are you getting the biome name from? the F3 debug screen?

**Comment by Y0ungSandwich** [comment]
F3, Minimpa, Biome Tweaker mod commad, etc. All the same.

**Comment by Hennamann** [comment]
I was never able to reproduce this issue… No longer supporting 1.12 so i'm going to close this issue.
