### ISSUE TITLE
[Feature Request] You can add biome color support?

### ISSUE THREAD

**Issue by Abo233** [Hennamann/Fog-World#8]
Let the fog change with the color of the biome

**Comment by Hennamann** [comment]
Hmmmm, might add this as a config option, i hope at some point to make it possible to set fog colors per biome using a Json system which could default to something like this…

Leaving this open to remind me.

**Comment by Hennamann** [comment]
It is now possible to set the color and density of the fog per biome using the new JSON configs. There are no defaults for this however, but i still consider this issue as resolved.
